package com.platzi.news.ui.theme

import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF4d4ec8)
val lightOnPrimary = Color(0xFFffffff)
val lightPrimaryContainer = Color(0xFFe1dfff)
val lightOnPrimaryContainer = Color(0xFF08006b)
val lightSecondary = Color(0xFF5d5c72)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFFADEBC)
val lightOnSecondaryContainer = Color(0xFFe2e0f9)
val lightTertiary = Color(0xFF795369)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFFFD8EC)
val lightOnTertiaryContainer = Color(0xFF2E1124)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFFFFBFF)
val lightOnBackground = Color(0xFF1C1B1F)
val lightSurface = Color(0xFFFFFBFF)
val lightOnSurface = Color(0xFF1C1B1F)
val lightSurfaceVariant = Color(0xFFE4E1EC)
val lightOnSurfaceVariant = Color(0xFF47464F)
val lightOutline = Color(0xFF777680)
val lightInverseOnSurface = Color(0xFFF3EFF4)
val lightInverseSurface = Color(0xFF313034)
val lightPrimaryInverse = Color(0xFFC1C1FF)

val darkPrimary = Color(0xFFC1C1FF)
val darkOnPrimary = Color(0xFF1A129A)
val darkPrimaryContainer = Color(0xFF3433AF)
val darkOnPrimaryContainer = Color(0xFFE1DFFF)
val darkSecondary = Color(0xFFC6C4DD)
val darkOnSecondary = Color(0xFF2F2F42)
val darkSecondaryContainer = Color(0xFF454559)
val darkOnSecondaryContainer = Color(0xFFE2E0F9)
val darkTertiary = Color(0xFFE9B9D3)
val darkOnTertiary = Color(0xFF46263A)
val darkTertiaryContainer = Color(0xFF5F3C51)
val darkOnTertiaryContainer = Color(0xFFFFD8EC)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF1C1B1F)
val darkOnBackground = Color(0xFFE5E1E6)
val darkSurface = Color(0xFF1C1B1F)
val darkOnSurface = Color(0xFFE5E1E6)
val darkSurfaceVariant = Color(0xFF47464F)
val darkOnSurfaceVariant = Color(0xFFC8C5D0)
val darkOutline = Color(0xFF918F9A)
val darkInverseOnSurface = Color(0xFF1C1B1F)
val darkInverseSurface = Color(0xFFE5E1E6)


val seed = Color(0xFF8183FF)
